"""migrate replycomment

Revision ID: b7997480de8c
Revises: 5993579345eb
Create Date: 2022-10-24 15:05:08.619428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7997480de8c'
down_revision = '5993579345eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replycomment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.String(length=120), nullable=True),
    sa.Column('image_url', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('commentary_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commentary_id'], ['commentary.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('commentary', sa.Column('message', sa.String(length=120), nullable=True))
    op.drop_column('commentary', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commentary', sa.Column('description', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('commentary', 'message')
    op.drop_table('replycomment')
    # ### end Alembic commands ###
