"""add foreignKey in usermodel and property unique in email

Revision ID: d8a1ab14f364
Revises: 283d645c0196
Create Date: 2022-10-13 16:41:10.321821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a1ab14f364'
down_revision = '283d645c0196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_foreign_key(None, 'users', 'roles', ['rol_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
